update_interval = 15
update_retries = 3

[queue]
endpoint = "amqp://localhost:5672"
exchange_name = "news"
username = "admin"
password = "admin"

[[feeds]]
name = "Источник для разработки"
url = "http://localhost:4000/dev.rss"

[[feeds]]
name = "Главные новости OpenNET"
url = "https://www.opennet.ru/opennews/opennews_6_utf.rss"
active = false

[[feeds]]
name = "Новости / Хабр"
url = "https://habr.ru/ru/rss/news"
active = false
