services:
  rabbitmq:
    image: docker.io/library/rabbitmq:4.2-alpine
    hostname: rabbitmq-1
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      start_period: 5s
      start_interval: 5s
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  rabbitmq_data:
